#!/bin/sh

. /lib/functions.sh
. /lib/functions/network.sh

band_steer_helper="$1"
band="$(uci get fakemesh.default.band || echo none)"

band_steer_helper_switch()
{
    if [ "$band" = "6g" ]; then
        # Solo activar el helper si banda es 6G
        if [ "$band_steer_helper" = "usteer" ]; then
            uci delete usteer.@usteer[0].event_log_types 2>/dev/null
            uci delete usteer.@usteer[0].ssid_list 2>/dev/null
            uci commit usteer
            test -x /etc/init.d/dawn && {
                /etc/init.d/dawn enabled && /etc/init.d/dawn disable
                /etc/init.d/dawn running && /etc/init.d/dawn stop
            }
            test -x /etc/init.d/usteer && {
                /etc/init.d/usteer enabled || /etc/init.d/usteer enable
                /etc/init.d/usteer running || /etc/init.d/usteer start
            }
        elif [ "$band_steer_helper" = "dawn" ]; then
            test -x /etc/init.d/usteer && {
                /etc/init.d/usteer enabled && /etc/init.d/usteer disable
                /etc/init.d/usteer running && /etc/init.d/usteer stop
            }
            test -x /etc/init.d/dawn && {
                /etc/init.d/dawn enabled || /etc/init.d/dawn enable
                /etc/init.d/dawn running || /etc/init.d/dawn start
            }
        else # "none" u otro valor
            test -x /etc/init.d/dawn && {
                /etc/init.d/dawn enabled && /etc/init.d/dawn disable
                /etc/init.d/dawn running && /etc/init.d/dawn stop
            }
            test -x /etc/init.d/usteer && {
                /etc/init.d/usteer enabled && /etc/init.d/usteer disable
                /etc/init.d/usteer running && /etc/init.d/usteer stop
            }
        fi
    else
        # Si la banda NO es 6G, desactiva ambos helpers
        test -x /etc/init.d/dawn && {
            /etc/init.d/dawn enabled && /etc/init.d/dawn disable
            /etc/init.d/dawn running && /etc/init.d/dawn stop
        }
        test -x /etc/init.d/usteer && {
            /etc/init.d/usteer enabled && /etc/init.d/usteer disable
            /etc/init.d/usteer running && /etc/init.d/usteer stop
        }
    fi
}

[ "$1" = "band_steer_helper_switch" ] && {
    band_steer_helper_switch
    exit 0
}
